/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Products {
  created_at: Generated<Timestamp>;
  deleted_at: Timestamp | null;
  id: Generated<number>;
  name: string;
  price: number;
  stock: number;
  updated_at: Generated<Timestamp | null>;
}

export interface Transactions {
  created_at: Generated<Timestamp>;
  deleted_at: Timestamp | null;
  id: Generated<number>;
  payment_method: string | null;
  payment_status: number | null;
  price: number;
  product_id: number;
  product_name: string;
  quantity: number;
  status: string;
  total_price: number;
  updated_at: Generated<Timestamp | null>;
  user_phone: string;
}

export interface DB {
  products: Products;
  transactions: Transactions;
}
